source: "./source" # or could be a directory eg. ./examples

#repos:
#  revealjs: 'https://github.com/hakimel/reveal.js/archive/3.6.0.tar.gz'
#  revealjs-backend: 'https://github.com/asciidoctor/asciidoctor-reveal.js/archive/master.zip'

attributes:
  backend: 'revealjs'

options:
  to_dir: './generated'
  safe: 'unsafe' # Required to avoid that the file to process is not loaded